version: "3.2"

services:
    database:
        build:
            context: ./docker/database
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/database/data:/var/lib/mysql
    php-fpm:
        build:
            context: ./docker/php-fpm
        depends_on:
            - database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
            - PIVOTAL_TRACKER_API_KEY=${PIVOTAL_TRACKER_API_KEY}
            - PIVOTAL_TRACKER_OWNER=${PIVOTAL_TRACKER_OWNER}
        volumes:
            - ./src/:/var/www
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./src:/var/www
            - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/etc/nginx/sites-available:/etc/nginx/sites-available
            - ./docker/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/logs:/var/logs
        depends_on:
            - php-fpm
        ports:
            - ${PORT}:80
            - 5432:443